name: üì¶ Build Genius Invokation (Beta version)
run-name: ${{ github.actor }} is building Genius Invokation (Beta version)

# This CI workflow is expected run at genius-invokation/genius-invokation-beta repository.
# Do NOT push on `beta` branch on the main repo.

on:
  push:
    branches: ["beta"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  Build-Core:
    name: ‚öôÔ∏è Build TypeScript Core
    runs-on: self-hosted
    env:
      SERVER_HOST: gi.xqm32.org
      WEB_CLIENT_BASE_PATH: /beta/
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Run Build
        run: |
          bun install
          bun run build -n standalone
      - name: Run Tests
        run: bun run test
      - name: "Upload artifact: Standalone frontend"
        uses: actions/upload-artifact@v4
        with:
          name: standalone-frontend
          path: packages/standalone/dist
  Deploy-Frontend:
    name: üåê Deploy Standalone Frontend
    needs: Build-Core
    runs-on: self-hosted
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: standalone-frontend
          path: dist
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Deploy to Vercel
        run: |
          cd dist
          bunx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
